### ISSUE TITLE
Avoid failing if __file__ doesnt exist / PyOxidizer support

### ISSUE THREAD

**Issue by jayvdb** [jackmaney/python-stdlib-list#25]
PyOxidizer breaks on `stdlib-list` as  it doesnt provide `__file__`   See indygreg/PyOxidizer#69 for more info about why, but the tl;dr version is `__file__` is an optional attribute and should not be relied upon.

e.g. at the moment this is what it looks like
```py
>>> import depfinder
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "depfinder", line 34, in <module>
  File "depfinder.main", line 41, in <module>
  File "stdlib_list", line 6, in <module>
  File "stdlib_list.base", line 6, in <module>
NameError: name '__file__' is not defined
```

**Comment by ocefpaf** [comment]
I never used `PyOxidizer` before. Good to know. Do you want to send a PR?
